#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448315587                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon512.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : " "                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : AI Powered Psychic Readings

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Foobar Creative                                
your_link                                 : https://foobarcreative.com                     
your_city                                 : Adelaide                                
email_address                             : support@gmail.com
facebook_username                         : mysticvisionsapp                                          
instagram_username                        : mysticvisions.app
twitter_username                          : mysticvisionsai
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Helena the Mystic
    description                           : A wise and patient mystic with the ability to perceive the future and the past. I use my intuitive gifts to offer guidance and insight to those who seek it.
    fontawesome_icon_name                 : #magic
    image_name                            : assets/mystic_avatar.png

  - title                                 : Susan the Astrologer
    description                           : With years of profound study and a deep understanding of the cosmos, Susan possesses the innate ability to unravel the celestial mysteries guiding our lives.
    fontawesome_icon_name                 : #mobile
    image_name                            : assets/astrologer_avatar.png
    
  - title                                 : Trevor the Tarot Reader
    description                           : A tarot reader with years of experience in divination and guiding others through the enigmatic realms of the tarot. I approach each reading with an open mind and a desire to assist and offer clarity.
    fontawesome_icon_name                 : #play-circle
    image_name                            : assets/tarot_reader_avatar.jpg

  - title                                 : Pythia the Oracle
    description                           : Known for her profound wisdom and intuitive powers. With a lineage steeped in spiritual knowledge, I possess the ability to peer into the fabric of time and provide glimpses of the future.
    fontawesome_icon_name                 : #sync
    image_name                            : assets/oracle_avatar.jpg

  - title                                 : Siakam the Seer
    description                           : The seer of finance and money, Siakam weaves profound wisdom into the tapestry of the future. Through cosmic insight, his words illuminate the path to prosperity.
    fontawesome_icon_name                 : #adjust
    image_name                            : assets/seer_avatar.jpg

  - title                                 : Clea the Wise Woman
    description                           : Clea, a wise woman whose intuition and wisdom delve deeply into matters of love and relationships. My soul's purpose is to guide others on their paths to fulfilling and harmonious connections.
    fontawesome_icon_name                 : #star
    image_name                            : assets/wise_woman_avatar.jpg

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Style
default_primary                           : "#E91E63"
dark_primary                              : "#C2185B"
accent                                    : "#FF4081"

# Theme Settings
topbar_color                              : "#C2185B"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/stars_and_swirl.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.2

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : dark_primary #  "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#E91E63"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"














####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
